import { Video } from './types';

export const DUMMY_VIDEOS: Video[] = [
  {
    id: '1',
    youtubeId: 'O1g3pA7a6w4',
    title: 'Midnight Praise (Tasbeha) - Joyful Hymns',
    description: 'Join us for a beautiful midnight praise session featuring the choir of St. Refka Church.',
    category: 'Hymns',
    thumbnail: 'https://img.youtube.com/vi/O1g3pA7a6w4/maxresdefault.jpg',
    views: 12500,
    createdAt: '2023-10-15T10:00:00Z',
  },
  {
    id: '2',
    youtubeId: 'rXhYtY_aZqE',
    title: 'The Virtue of Patience - Fr. Daoud Lamei',
    description: 'A spiritual contemplation on the life of St. Refka and the virtue of bearing the cross with joy.',
    category: 'Sermons',
    thumbnail: 'https://img.youtube.com/vi/rXhYtY_aZqE/maxresdefault.jpg',
    views: 8543,
    createdAt: '2023-09-20T14:30:00Z',
  },
  {
    id: '3',
    youtubeId: '2uO3zK3u2hY',
    title: 'Sunday Divine Liturgy - St. Basil',
    description: 'Full streaming of the Sunday Divine Liturgy celebrated at St. Refka Church.',
    category: 'Liturgies',
    thumbnail: 'https://img.youtube.com/vi/2uO3zK3u2hY/maxresdefault.jpg',
    views: 3400,
    createdAt: '2023-11-05T09:15:00Z',
  },
  {
    id: '4',
    youtubeId: 'b_5j2F8o6zU',
    title: 'Story of Saint Refka for Kids',
    description: 'An animated story explaining the life and sainthood of St. Refka for our Sunday School children.',
    category: 'Kids',
    thumbnail: 'https://img.youtube.com/vi/b_5j2F8o6zU/maxresdefault.jpg',
    views: 12000,
    createdAt: '2023-08-12T16:20:00Z',
  },
  {
    id: '5',
    youtubeId: 'h9yK2G9vQ_g',
    title: 'Gospel of John - Chapter 1 Study',
    description: 'Weekly Bible study meeting discussing the theology of the Gospel of John.',
    category: 'Bible Study',
    thumbnail: 'https://img.youtube.com/vi/h9yK2G9vQ_g/maxresdefault.jpg',
    views: 4500,
    createdAt: '2024-02-21T15:00:00Z',
  }
];

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    mediaLibrary: 'Media Library',
    bibleStudies: 'Bible Studies',
    churchEvents: 'Church Events',
    settings: 'Settings',
    signOut: 'Sign Out',
    searchPlaceholder: 'Search sermons, hymns...',
    searchPlaceholderAdmin: 'Search media library...',
    addMedia: 'Add Media',
    welcomeUser: 'Browse sermons, hymns, and liturgies.',
    welcomeAdmin: 'Manage church content.',
    totalItems: 'Total Items',
    totalViews: 'Total Views',
    focus: 'Focus',
    noMedia: 'No media found',
    noMediaDesc: 'Try changing the filter or search term.',
    views: 'views',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    darkModeDesc: 'Switch between light and dark themes',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    churchName: 'St. Refka Church',
    mediaCenter: 'Media Center',
    deleteConfirm: 'Are you sure you want to delete this video?',
    categories: {
      All: 'All',
      Sermons: 'Sermons',
      Liturgies: 'Liturgies',
      'Bible Study': 'Bible Study',
      'El Hekaya': 'El Hekaya w Mafiha',
      'Youth Meeting': 'Youth Meeting',
      'Ma3loma': "Ma3loma 3al Mashy",
      Kids: 'Kids'
    },
    // Add Media Modal
    addNewContent: 'Add New Content',
    youtubeUrl: 'YouTube URL',
    title: 'Title',
    category: 'Category',
    description: 'Description',
    addToLibrary: 'Add to Library',
    invalidYoutubeUrl: 'Invalid YouTube URL',
    videoTitlePlaceholder: 'Video title',
    descriptionPlaceholder: 'Brief description...',
    // User Management
    users: 'Users',
    userManagement: 'User Management',
    searchUsers: 'Search by name or email...',
    noUsersFound: 'No users found',
    admin: 'Admin',
    user: 'User',
    promoteToAdmin: 'Promote to Admin',
    demoteToUser: 'Demote to User',
    roleUpdated: 'Role updated successfully',
    totalUsers: 'Total Users',
    deleteUser: 'Delete User',
    deleteUserConfirm: 'Are you sure you want to delete this user? This action cannot be undone.',
    userDeleted: 'User deleted successfully',
    // Pagination & Sorting
    sortBy: 'Sort by',
    newest: 'Newest',
    oldest: 'Oldest',
    mostViewed: 'Most Viewed',
    previous: 'Previous',
    next: 'Next',
    pageOf: 'of',
    // Favorites
    favorites: 'Favorites',
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',
    noFavorites: 'No favorites yet',
    noFavoritesDesc: 'Videos you save will appear here.',
    // Church Events
    addEvent: 'Add Event',
    addNewEvent: 'Add New Event',
    eventName: 'Event Name',
    eventDate: 'Date',
    eventTime: 'Time',
    eventNamePlaceholder: 'e.g. Sunday Liturgy',
    addToCalendar: 'Add to Calendar',
    noEvents: 'No events yet',
    noEventsDesc: 'Church events will appear here.',
    deleteEventConfirm: 'Are you sure you want to delete this event?',
    // Phone Auth
    email: 'Email',
    phoneNumber: 'Phone Number',
    phonePlaceholder: '+1234567890',
    loginWithEmail: 'Login with Email',
    loginWithPhone: 'Login with Phone',
    emailOrPhone: 'Email or Phone',
    enterEmail: 'Enter your email',
    enterPhone: 'Enter your phone number',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    password: 'Password',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signUp: 'Sign up',
    signInLink: 'Sign in',
    registrationSuccess: 'Registration successful. Please check your email to confirm your address, then sign in.'
  },
  ar: {
    dashboard: 'لوحة التحكم',
    mediaLibrary: 'مكتبة الوسائط',
    bibleStudies: 'دراسات الكتاب المقدس',
    churchEvents: 'مناسبات الكنيسة',
    settings: 'الإعدادات',
    signOut: 'تسجيل الخروج',
    searchPlaceholder: 'ابحث عن العظات والترانيم...',
    searchPlaceholderAdmin: 'ابحث في مكتبة الوسائط...',
    addMedia: 'إضافة وسائط',
    welcomeUser: 'تصفح العظات والترانيم والقداسات.',
    welcomeAdmin: 'إدارة محتوى الكنيسة.',
    totalItems: 'إجمالي العناصر',
    totalViews: 'إجمالي المشاهدات',
    focus: 'التركيز',
    noMedia: 'لا يوجد وسائط',
    noMediaDesc: 'حاول تغيير الفلتر أو مصطلح البحث.',
    views: 'مشاهدة',
    appearance: 'المظهر',
    darkMode: 'الوضع الداكن',
    darkModeDesc: 'التبديل بين المظهر الفاتح والداكن',
    light: 'فاتح',
    dark: 'داكن',
    language: 'اللغة',
    churchName: 'كنيسة القديسة رفقة',
    mediaCenter: 'المركز الإعلامي',
    deleteConfirm: 'هل أنت متأكد أنك تريد حذف هذا الفيديو؟',
    categories: {
      All: 'الكل',
      Sermons: 'العظات',
      Liturgies: 'القداسات',
      'Bible Study': 'دراسة الكتاب المقدس',
      'El Hekaya': 'الحكاية و ما فيها',
      'Youth Meeting': 'اجتماع الشباب',
      'Ma3loma': 'معلومة ع الماشي',
      Kids: 'الأطفال'
    },
    // Add Media Modal
    addNewContent: 'إضافة محتوى جديد',
    youtubeUrl: 'رابط يوتيوب',
    title: 'العنوان',
    category: 'التصنيف',
    description: 'الوصف',
    addToLibrary: 'إضافة إلى المكتبة',
    invalidYoutubeUrl: 'رابط يوتيوب غير صالح',
    videoTitlePlaceholder: 'عنوان الفيديو',
    descriptionPlaceholder: 'وصف مختصر...',
    // User Management
    users: 'المستخدمون',
    userManagement: 'إدارة المستخدمين',
    searchUsers: 'ابحث بالاسم أو البريد الإلكتروني...',
    noUsersFound: 'لا يوجد مستخدمون',
    admin: 'مسؤول',
    user: 'مستخدم',
    promoteToAdmin: 'ترقية إلى مسؤول',
    demoteToUser: 'تخفيض إلى مستخدم',
    roleUpdated: 'تم تحديث الدور بنجاح',
    totalUsers: 'إجمالي المستخدمين',
    deleteUser: 'حذف المستخدم',
    deleteUserConfirm: 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.',
    userDeleted: 'تم حذف المستخدم بنجاح',
    // Pagination & Sorting
    sortBy: 'ترتيب حسب',
    newest: 'الأحدث',
    oldest: 'الأقدم',
    mostViewed: 'الأكثر مشاهدة',
    previous: 'السابق',
    next: 'التالي',
    pageOf: 'من',
    // Favorites
    favorites: 'المفضلة',
    addToFavorites: 'إضافة إلى المفضلة',
    removeFromFavorites: 'إزالة من المفضلة',
    noFavorites: 'لا توجد مفضلات بعد',
    noFavoritesDesc: 'ستظهر الفيديوهات المحفوظة هنا.',
    // Church Events
    addEvent: 'إضافة مناسبة',
    addNewEvent: 'إضافة مناسبة جديدة',
    eventName: 'اسم المناسبة',
    eventDate: 'التاريخ',
    eventTime: 'الوقت',
    eventNamePlaceholder: 'مثال: القداس الأحدي',
    addToCalendar: 'إضافة إلى التقويم',
    noEvents: 'لا توجد مناسبات بعد',
    noEventsDesc: 'ستظهر مناسبات الكنيسة هنا.',
    deleteEventConfirm: 'هل أنت متأكد أنك تريد حذف هذه المناسبة؟',
    // Phone Auth
    email: 'البريد الإلكتروني',
    phoneNumber: 'رقم الهاتف',
    phonePlaceholder: '+1234567890',
    loginWithEmail: 'تسجيل بالبريد',
    loginWithPhone: 'تسجيل بالهاتف',
    emailOrPhone: 'البريد أو الهاتف',
    enterEmail: 'أدخل بريدك الإلكتروني',
    enterPhone: 'أدخل رقم هاتفك',
    fullName: 'الاسم الكامل',
    emailAddress: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    createAccount: 'إنشاء حساب',
    forgotPassword: 'نسيت كلمة المرور؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    signUp: 'سجل الآن',
    signInLink: 'تسجيل الدخول',
    registrationSuccess: 'تم التسجيل بنجاح. يرجى التحقق من بريدك الإلكتروني لتأكيد عنوانك، ثم سجل الدخول.'
  }
};