import { Video } from './types';

export const DUMMY_VIDEOS: Video[] = [
  {
    id: '1',
    youtubeId: 'O1g3pA7a6w4',
    title: 'Midnight Praise (Tasbeha) - Joyful Hymns',
    description: 'Join us for a beautiful midnight praise session featuring the choir of St. Refka Church.',
    category: 'Hymns',
    thumbnail: 'https://img.youtube.com/vi/O1g3pA7a6w4/maxresdefault.jpg',
    views: 12500,
    createdAt: '2023-10-15T10:00:00Z',
  },
  {
    id: '2',
    youtubeId: 'rXhYtY_aZqE',
    title: 'The Virtue of Patience - Fr. Daoud Lamei',
    description: 'A spiritual contemplation on the life of St. Refka and the virtue of bearing the cross with joy.',
    category: 'Sermons',
    thumbnail: 'https://img.youtube.com/vi/rXhYtY_aZqE/maxresdefault.jpg',
    views: 8543,
    createdAt: '2023-09-20T14:30:00Z',
  },
  {
    id: '3',
    youtubeId: '2uO3zK3u2hY',
    title: 'Sunday Divine Liturgy - St. Basil',
    description: 'Full streaming of the Sunday Divine Liturgy celebrated at St. Refka Church.',
    category: 'Liturgies',
    thumbnail: 'https://img.youtube.com/vi/2uO3zK3u2hY/maxresdefault.jpg',
    views: 3400,
    createdAt: '2023-11-05T09:15:00Z',
  },
  {
    id: '4',
    youtubeId: 'b_5j2F8o6zU',
    title: 'Story of Saint Refka for Kids',
    description: 'An animated story explaining the life and sainthood of St. Refka for our Sunday School children.',
    category: 'Kids',
    thumbnail: 'https://img.youtube.com/vi/b_5j2F8o6zU/maxresdefault.jpg',
    views: 12000,
    createdAt: '2023-08-12T16:20:00Z',
  },
  {
    id: '5',
    youtubeId: 'h9yK2G9vQ_g',
    title: 'Gospel of John - Chapter 1 Study',
    description: 'Weekly Bible study meeting discussing the theology of the Gospel of John.',
    category: 'Bible Study',
    thumbnail: 'https://img.youtube.com/vi/h9yK2G9vQ_g/maxresdefault.jpg',
    views: 4500,
    createdAt: '2024-02-21T15:00:00Z',
  }
];

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    mediaLibrary: 'Media Library',
    bibleStudies: 'Bible Studies',
    churchEvents: 'Church Events',
    settings: 'Settings',
    signOut: 'Sign Out',
    searchPlaceholder: 'Search sermons, hymns...',
    searchPlaceholderAdmin: 'Search media library...',
    addMedia: 'Add Media',
    welcomeUser: 'Browse sermons, hymns, and liturgies.',
    welcomeAdmin: 'Manage church content.',
    totalItems: 'Total Items',
    totalViews: 'Total Views',
    focus: 'Focus',
    noMedia: 'No media found',
    noMediaDesc: 'Try changing the filter or search term.',
    views: 'views',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    darkModeDesc: 'Switch between light and dark themes',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    churchName: 'St. Refka Church',
    mediaCenter: 'Media Center',
    deleteConfirm: 'Are you sure you want to delete this video?',
    categories: {
      All: 'All',
      Sermons: 'Sermons',
      Hymns: 'Hymns',
      Liturgies: 'Liturgies',
      'Bible Study': 'Bible Study',
      Kids: 'Kids',
      Events: 'Events'
    },
    // Add Media Modal
    addNewContent: 'Add New Content',
    youtubeUrl: 'YouTube URL',
    title: 'Title',
    category: 'Category',
    description: 'Description',
    addToLibrary: 'Add to Library',
    invalidYoutubeUrl: 'Invalid YouTube URL',
    videoTitlePlaceholder: 'Video title',
    descriptionPlaceholder: 'Brief description...'
  },
  ar: {
    dashboard: 'لوحة التحكم',
    mediaLibrary: 'مكتبة الوسائط',
    bibleStudies: 'دراسات الكتاب المقدس',
    churchEvents: 'أحداث الكنيسة',
    settings: 'الإعدادات',
    signOut: 'تسجيل الخروج',
    searchPlaceholder: 'ابحث عن العظات والترانيم...',
    searchPlaceholderAdmin: 'ابحث في مكتبة الوسائط...',
    addMedia: 'إضافة وسائط',
    welcomeUser: 'تصفح العظات والترانيم والقداسات.',
    welcomeAdmin: 'إدارة محتوى الكنيسة.',
    totalItems: 'إجمالي العناصر',
    totalViews: 'إجمالي المشاهدات',
    focus: 'التركيز',
    noMedia: 'لا يوجد وسائط',
    noMediaDesc: 'حاول تغيير الفلتر أو مصطلح البحث.',
    views: 'مشاهدة',
    appearance: 'المظهر',
    darkMode: 'الوضع الداكن',
    darkModeDesc: 'التبديل بين المظهر الفاتح والداكن',
    light: 'فاتح',
    dark: 'داكن',
    language: 'اللغة',
    churchName: 'كنيسة القديسة رفقة',
    mediaCenter: 'المركز الإعلامي',
    deleteConfirm: 'هل أنت متأكد أنك تريد حذف هذا الفيديو؟',
    categories: {
      All: 'الكل',
      Sermons: 'العظات',
      Hymns: 'الترانيم',
      Liturgies: 'القداسات',
      'Bible Study': 'دراسة الكتاب المقدس',
      Kids: 'الأطفال',
      Events: 'المناسبات'
    },
    // Add Media Modal
    addNewContent: 'إضافة محتوى جديد',
    youtubeUrl: 'رابط يوتيوب',
    title: 'العنوان',
    category: 'التصنيف',
    description: 'الوصف',
    addToLibrary: 'إضافة إلى المكتبة',
    invalidYoutubeUrl: 'رابط يوتيوب غير صالح',
    videoTitlePlaceholder: 'عنوان الفيديو',
    descriptionPlaceholder: 'وصف مختصر...'
  }
};